name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets: inherit
    with:
      repo_config: true
      repo_description: "Shared renovate configuration and GitHub Action"
      required_approving_review_count: 0
