---
name: Renovate
on:
  schedule:
    - cron: "2 * * * *"
  pull_request:
    branches:
      - master
      - main

env:
  LOG_LEVEL: debug
  # renovate: datasource=docker depName=renovate packageName=ghcr.io/renovatebot/renovate
  RENOVATE_VERSION: 38.59.3

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      # https://github.com/philips-software/app-token-action
      - name: Generate GitHub App installation token
        uses: philips-software/app-token-action@9f5d57062c9f2beaffafaa9a34f66f824ead63a9 # v2.0.0
        id: app_token
        with:
          # https://github.com/apps/balena-renovate
          # https://github.com/organizations/product-os/settings/apps/balena-renovate
          app_id: ${{ vars.RENOVATE_APP_ID || '335686' }}
          app_base64_private_key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY_B64 }}
          auth_type: installation

      - name: Enable dry-run
        run: echo "RENOVATE_DRY_RUN=full" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'

      # https://github.com/renovatebot
      - uses: renovatebot/github-action@630a255a1f2f56c8d8ce160bed3e3ca577ca53e2 # v40.2.7
        with:
          # https://docs.renovatebot.com/configuration-options
          # https://docs.renovatebot.com/self-hosted-configuration
          configurationFile: default.json
          token: ${{ steps.app_token.outputs.token }}
          renovate-version: ${{ env.RENOVATE_VERSION }}
        env:
          RENOVATE_DRY_RUN: ${{ env.RENOVATE_DRY_RUN }}
          RENOVATE_HOST_RULES: |
            [
              {
                "hostType": "docker",
                "username": "${{ secrets.DOCKERHUB_USER }}",
                "password": "${{ secrets.DOCKERHUB_TOKEN }}"
              },
              {
                "hostType": "docker",
                "matchHost": "ghcr.io",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              }
            ]
