---
name: Renovate
on:
  schedule:
    - cron: '2 * * * *'
  pull_request:
    branches:
      - master

env:
  LOG_LEVEL: debug

jobs:
  renovate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3

      - name: Enable dry-run
        run: echo "RENOVATE_DRY_RUN=full" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'

      # https://github.com/renovatebot
      - uses: renovatebot/github-action@a1f801063f9dd02eb35661ca3b6ac3fe678a7fb6 # v34.76.1
        with:
          # https://docs.renovatebot.com/configuration-options
          configurationFile: default.json
          # FIXME: switch to ephemeral token
          token: ${{ secrets.FLOWZONE_TOKEN }}
        env:
          RENOVATE_DRY_RUN: ${{ env.RENOVATE_DRY_RUN }}
          RENOVATE_HOST_RULES: |
            [
              {
                "hostType": "docker",
                "username": "${{ secrets.DOCKERHUB_USER }}",
                "password": "${{ secrets.DOCKERHUB_TOKEN }}"
              },
              {
                "hostType": "docker",
                "matchHost": "ghcr.io",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              }
            ]
