---
name: Renovate
on:
  schedule:
    - cron: "2 * * * *"
  pull_request:
    branches:
      - master
      - main

env:
  LOG_LEVEL: debug

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      # https://github.com/philips-software/app-token-action
      - name: Generate GitHub App installation token
        uses: philips-software/app-token-action@a37926571e4cec6f219e06727136efdd073d8657 # v1.1.2
        id: app_token
        with:
          # https://github.com/apps/balena-renovate
          # https://github.com/organizations/product-os/settings/apps/balena-renovate
          app_id: ${{ vars.RENOVATE_APP_ID || '335686' }}
          app_base64_private_key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY_B64 }}
          auth_type: installation

      - name: Enable dry-run
        run: echo "RENOVATE_DRY_RUN=full" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'

      # https://github.com/renovatebot
      - uses: renovatebot/github-action@23a02fe7be9e93f857a953cc8162e57d2c8401ef # v39.0.1
        with:
          # https://docs.renovatebot.com/configuration-options
          # https://docs.renovatebot.com/self-hosted-configuration
          configurationFile: default.json
          token: ${{ steps.app_token.outputs.token }}
        env:
          RENOVATE_DRY_RUN: ${{ env.RENOVATE_DRY_RUN }}
          RENOVATE_HOST_RULES: |
            [
              {
                "hostType": "docker",
                "username": "${{ secrets.DOCKERHUB_USER }}",
                "password": "${{ secrets.DOCKERHUB_TOKEN }}"
              },
              {
                "hostType": "docker",
                "matchHost": "ghcr.io",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              }
            ]
